name = "sdlada_ttf"
description = "Ada 2022 bindings to SDL2_ttf."
version = "0.1.0-dev"

authors = ["Luke A. Guest"]
maintainers = ["Luke A. Guest <laguest@archeia.com>"]
maintainers-logins = ["Lucretia"]
licenses = "Zlib"
website = ""
tags = ["sdl2", "ttf", "fonts"]

[[depends-on]]
  sdlada = "=2.5.23"
  libsdl2_ttf = "^2.0.0"

#[[pins]] # TODO: Remove
#  sdlada = { path = "../sdlada" }
